---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---



```{r}
library(ggplot2)
library(olsrr)
library(ggplot2)
bf = read.csv("BodyFat.csv")
head(bf)
```

```{r }
# Siri Equation
bf$bf_predict = 495/bf$DENSITY-450
bf_outlier = order(abs(bf$bf_predict-bf$BODYFAT), decreasing = TRUE)[1:10]
bf$outlier = 1:dim(bf)[1] %in% bf_outlier
bf[bf_outlier,c("BODYFAT","bf_predict")]
```

```{r }
# outliers 48,96 have top2 diff, 182 has impossible values
bf_outlier = c(48,96,182)
```

```{r }
#BMI Formula
bf$bmi_predict = 0.4536*bf$WEIGHT/(bf$HEIGHT*0.0254)^2
bmi_outlier = order(abs(bf$bmi_predict-bf$ADIPOSITY), decreasing = TRUE)[1:10]
bf$outlier = 1:dim(bf)[1] %in% bmi_outlier
bf[bmi_outlier,c("ADIPOSITY","bmi_predict","WEIGHT","HEIGHT")]
```



```{r }
# outliers 42,163,221 have top3 diff
bmi_outlier = c(42,163,221)
bf = bf[-c(bf_outlier,bmi_outlier), ]
```

```{r }
for(x in 2:17){
  p = ggplot(data = bf,aes(x=bf[,x]))+
  geom_boxplot()+
  xlab(colnames(bf)[x]) 
  print(p)
}
#ALL look normal
```

```{r }
lmfit <- lm(BODYFAT~DENSITY+AGE+WEIGHT+HEIGHT+ADIPOSITY+NECK+CHEST+ABDOMEN+WRIST,data=bf)
all_posible = ols_step_all_possible(lmfit)
all_posible
```
```{r }
# other criteria like AIC perfoms worse than adjr
top10 = all_posible[order(all_posible$adjr,decreasing = TRUE),][1:10,]
top10
```

```{r }

kfold <- function(data,expr,fold){
  mse <- c()
  adj_r_suqare <- c()
  for(i in 1:fold){
    test_index <- sample(1:nrow(data),floor(nrow(data)/10))
    testdata <- data[test_index,];traindata <- data[-test_index,]
    model_test <- lm(expr  ,data = traindata)
    adj_r_suqare[i] <- summary(model_test)$adj.r.squared
    predicted.values <- predict(object = model_test,testdata)
    mse[i] <- sqrt(mean((predicted.values-testdata$BODYFAT)^2))
  }
  
  cat('\n')
  print(expr)
  cat('avg_adj_r_square:',mean(adj_r_suqare),'\n')
  cat('avg_mse:',mean(mse),'\n')
  cat('sd_mse:',sd(mse),'\n')
}

# use abdomen as waist
# upcoming: convenient
kfold(bf,BODYFAT~log(HEIGHT- NECK)+log(ABDOMEN), 5)

# if no NECK, substitude:
kfold(bf,BODYFAT~log(HEIGHT)+log(ABDOMEN), 5)

# from top10, we choose the minimun num of predictors
# upcoming: accurate
kfold(bf,BODYFAT ~ DENSITY+WEIGHT+ADIPOSITY, 5)
```

